# uv run theseus submit 1B_fw_mnli_qqp_sst2_siqa ./configs/continual/abcd.yaml -p continual -g e0 --mem 128G

architecture:
  n_embd: 2048
  n_layers: 16
  bias: true
  dropout: 0.0
  n_head: 16
  rope: true
  block_size: 512
  vocab_size: 100288
  vram_calib_factor: 1.0
eval:
  evaluations:
  - mnli
  - qqp
  - sst2
  - siqa
tokenizer:
  backend: tiktoken
  name: cl100k_base
  huggingface:
    use_fast: true
    use_remote_code: false
optimization:
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  lr: 0.0003
  warmup_pct: 0.01
  decay_pct: 0.01
  constant_pct: 0.3
training:
  batch_size: 512
  per_device_batch_size: -1
  tokens:
  - 1000000000
  - 100000000
  - 100000000
  - 100000000
  - 100000000
  validation: false
  evaluate: true
  dataset:
  - - name: fineweb
      rate: 1.0
      style: PMD
      suffix: ''
  - - name: mnli
      rate: 1.0
      style: PADDED
      suffix: ''
  - - name: qqp
      rate: 1.0
      style: PADDED
      suffix: ''
  - - name: sst2
      rate: 1.0
      style: PADDED
      suffix: ''
  - - name: siqa
      rate: 1.0
      style: PADDED
      suffix: ''
  validation_steps: 2048
logging:
  report_interval: 32
  checkpoint_interval: 4096
  validation_interval: 1024
  wandb: true
job: continual/train/abcd
request:
  chip: h200
  min_chips: 1
